#define STACKSIZE 16
#define MEMORYSIZE 4096
#define VARIABLE_COUNT 16
#define KEYCOUNT 16
#define CARRY_FLAG_INDEX 15
#define SCALE 15
#define ROWS 32
#define COLUMNS 64
#define REFRESHRATE 16
#define PROGRAM_START 0x200
#define DEBUG_LINES 20
#define DEBUG_KEY_COUNT 3
#define CLOCK_RATE 1

